CREATE DATABASE IF NOT EXISTS `SPIKE-OSGI_WAB`;

USE `SPIKE-OSGI_WAB`;

DROP TABLE IF EXISTS `STOCK`;
CREATE TABLE `STOCK` (
  `STOCK_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `STOCK_CODE` VARCHAR(10) NOT NULL,
  `STOCK_NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`STOCK_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `STOCK` (`STOCK_CODE`, `STOCK_NAME`) VALUES
("APPLE", "Apple"), ("GOOGLE", "Google"), ("BLACKBERRY", "Blackberry");